### ISSUE TITLE
Add demo to codepen

### ISSUE THREAD

**Issue by safaorhan** [hbirler/dEngine#1]
Hello, nice work!

Feature request:

Can you provide use with a demo on codepen / jsfiddle?

Thanks

**Comment by hbirler** [comment]
Hi! Thanks for the interest. I published the demo to Github-Pages and linked to it in README.md. However, I am not maintaining this project anymore, so use it at your own risk! It was only for a hackathon-like programming challenge, so I wouldn't call the code reliable.
